### PR TITLE
Dev into Main

### PR DESCRIPTION
**Pull request by rebaz36**
# PR Description:
## In the Last Few Days we've implemented the followings on the dev Branch

- KanBan Board Setup ✅ 
- Repository SetUp ✅ 
- Linters ✅ 
- Header & Footer ✅ 
- Webpack & Jest ✅ 
- Add GhibiliAPI Class for interaction with Ghibili API ✅ 
- Displaying List of Items on the Home Screen ✅ 
- Add Involvement Class for interaction with Involvement API ✅ 
- Add Items Counter ✅ 
- Add Comments Counter ✅ 
- Display Likes ✅ 
- Display Comments ✅ 
- Add Likes ✅ 
- Add Comment ✅ 
- Add Test for Item Counter ✅ 
- Add Test for Comments Counter ✅

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and Organized code
:heavy_check_mark:  Good job with UI
:heavy_check_mark:  Good job with test coverage
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

- [ ] As it is a [requirement ](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md)for this project, 

### Project documentation
Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

  - A description of the project.
  - A demo of the project features.
  - You should also highlight some interesting piece of code or something you built that you are very proud of.
  - You all should appear in the video and talk about the project.
   For recording the video you can use the Zoom recording features while in a call with your peers.
Please kindly record a video presentation of your project. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebaz36** [comment]
Hey @t-yanick thanks for the Note i added the Project Documentation Video To the Readme File

**Review by t-yanick — APPROVED** [review]
Hi Team, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Good job with video presentation
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebaz36** [comment]
Thanks @t-yanick

**Pull request merged**
